name: mi_argentina
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/img/iconoCobros.png
    - lib/img/iconoDocumentos.png
    - lib/img/iconoHijos.png
    - lib/img/iconoSalud.png
    - lib/img/iconoTrabajo.png
    - lib/img/iconoTramites.png
    - lib/img/iconoTurnos.png
    - lib/img/iconoVehiculos.png
    - lib/img/logoMiArg.png
    - lib/img/logoPerfil.png
    - lib/img/menuNav.png
    - lib/img/solicitarTurno.png

